- hosts: all
  become: true
  tasks:
  - name: Gather OS facts
    setup:

  - name: Install packages for Amazon Linux
    ansible.builtin.dnf:
      name:
        - httpd
        - mariadb105-server
        - wget
        - php
        - php-mysqlnd
        - php-fpm
        - php-mysqli
        - php-json
        - php-devel
      state: present 
    when: ansible_os_family == "Amazon"

  - name: Start and enable httpd and mariadb services
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:  
        - httpd
        - mariadb
    when: ansible_os_family == "Amazon"

  - name: Download the latest version of WordPress
    ansible.builtin.get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/latest.tar.gz

  - name: Extract WordPress
    ansible.builtin.unarchive:
      src: /tmp/latest.tar.gz
      dest: /tmp
      remote_src: true

  - name: Copy files from the WordPress directory to the web root
    ansible.builtin.copy:
      src: /tmp/wordpress/
      dest: /var/www/html
      owner: apache
      group: apache
      mode: '0755'
      remote_src: true
    when: ansible_os_family == "Amazon"
  
  - name: Remove index.html
    ansible.builtin.file:
      path: /var/www/html/index.html  # Adjust this path to the actual location of index.html
      state: absent

  - name: Make sure the httpd and mariadb105 services are running
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    loop:  
        - httpd
        - mariadb
    when: ansible_os_family == "RedHat"

  - name: install PyMySQL
    ansible.builtin.dnf:
      name: python3-pymysql
      state: present
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: Create a database
    community.mysql.mysql_db:
      name: queen
      state: present
      login_unix_socket: /var/lib/mysql/mysql.sock
    when: ansible_os_family == "RedHat"

  - name: Create a database user and grant privileges
    community.mysql.mysql_user:
      name: freddie
      password: freddie123
      priv: "queen.*:ALL"
      state: present
    when: ansible_os_family == "RedHat"

 

  

      