#ubuntu       - debian family;   apt;       apache2;    mysql-server;         www-data;  
#amazon linux - redhat family;   yum/dnf;   httpd;      mariadb105-server;    apache;  

- hosts: redhat
  become: true
  gather_facts: yes
    
  roles:
    - apache
    - database
    - php
    - wordpress
    


    
   



# tasks:
  # - name: Show OS Family
  #   debug:
  #     msg: "The OS family is {{ ansible_os_family }}"



 


  

      