#ubuntu       - debian family;   apt;       apache2;    mysql-server;         www-data;  
#amazon linux - redhat family;   yum/dnf;   httpd;      mariadb105-server;    apache;  

- hosts: all
  become: true
  tasks:
  - name: Gather OS facts
    setup:
    
  roles:
    - apache
    - php
    - wordpress
    - database


    
   







 


  

      